# Create First Iteration of data:

In [1]:
import pandas as pd
import numpy as np

from pathlib import Path

In [2]:
# 2 reports for base result:
base_reports = ['41866595.xlsx', '41866596.xlsx']
df_1 = pd.read_excel('./data/source/'+base_reports[0])
df_1['report_number'] = '41866595'
df_2 = pd.read_excel('./data/source/'+base_reports[1])
df_2['report_number'] = '41866596'
print(f'df_1.shape={df_1.shape}')
print(f'df_2.shape={df_2.shape}')
df_result = df_1.copy()
df_result = df_result.drop(df_result.index)
# concat 1st 2 files:
df_result = pd.concat([df_1, df_2], ignore_index=True)
print(f'df_result.shape={df_result.shape}')
# save to csv:
df_result.to_csv('./data/result/df_result.csv', index=False, sep='|')

df_1.shape=(23380, 55)
df_2.shape=(853, 55)
df_result.shape=(24233, 55)

# Addition of new report file

In [3]:
# read from csv:
df_result = pd.read_csv('./data/result/df_result.csv', sep='|')
print(f'df_result.shape = {df_result.shape}')
df_result.head(1)

df_result.shape = (24233, 55)

C:\Users\abal\AppData\Local\Temp\ipykernel_3536\1320433426.py:2: DtypeWarning: Columns (53) have mixed types. Specify dtype option on import or set low_memory=False.
  df_result = pd.read_csv('./data/result/df_result.csv', sep='|')

,№,Номер поставки,Предмет,Код номенклатуры,Бренд,Артикул поставщика,Название,Размер,Баркод,Тип документа,...,Страна,Тип коробов,Номер таможенной декларации,Код маркировки,ШК,Rid,Srid,Возмещение издержек по перевозке,Организатор перевозки,report_number
0,17003963095,11082612,Юбки,44573138,Round&Round,YBBHblackleatherчернаякожаная,Юбка кожаная миди карандаш с разрезом длинная,L,2020837551009,Продажа,...,Россия,Микс,NaN,NaN,9317390808,6.037198e+11,56668891080620887.0.0,NaN,NaN,41866595

In [4]:
reports_uploaded = list(df_result['report_number'].unique())
reports_uploaded

[41866595, 41866596]

In [5]:
def check_what_reports_are_new(reports_uploaded):
    folder_path = './data/source/'
    folder = Path(folder_path)
    for file in folder.iterdir():
        if file.is_file():
            file_name = file.name
            report_name = int(file_name.replace('.xlsx', ''))
            # check whether report number already uploaded:
            new_reports = []
            if report_name not in reports_uploaded:
                print(f'Found new report: {report_name}')
                new_reports.append(report_name)
    return new_reports

# add to datasource:
def add_to_datasource(new_reports):
    folder_path = './data/source/'
    for report_name in new_reports:
        file_name = report_name + '.xlsx'
        df_report = pd.read_excel(folder_path+file_name)
        df_report['report_number'] = report_name        
        # concat to main file:
        df_result = pd.concat([df_result, df_report], ignore_index=True)

Found new report: 111
df_report.shape: (25260, 54)
df_result.shape: (49493, 55)
---------------

# Addition of new file with changes:
- if new file does not have some columns: it is not a problem
- if new file has some new columns:

In [15]:
# read from csv:
df_result = pd.read_csv('./data/result/df_result.csv', sep='|')
print(f'df_result.shape = {df_result.shape}')
df_result.head(1)

df_result.shape = (24233, 55)

C:\Users\abal\AppData\Local\Temp\ipykernel_3536\1320433426.py:2: DtypeWarning: Columns (53) have mixed types. Specify dtype option on import or set low_memory=False.
  df_result = pd.read_csv('./data/result/df_result.csv', sep='|')

,№,Номер поставки,Предмет,Код номенклатуры,Бренд,Артикул поставщика,Название,Размер,Баркод,Тип документа,...,Страна,Тип коробов,Номер таможенной декларации,Код маркировки,ШК,Rid,Srid,Возмещение издержек по перевозке,Организатор перевозки,report_number
0,17003963095,11082612,Юбки,44573138,Round&Round,YBBHblackleatherчернаякожаная,Юбка кожаная миди карандаш с разрезом длинная,L,2020837551009,Продажа,...,Россия,Микс,NaN,NaN,9317390808,6.037198e+11,56668891080620887.0.0,NaN,NaN,41866595

In [16]:
df_111 = pd.read_excel('./data/source/111.xlsx')
df_111['report_number'] = 111
df_111.head(1)

,№,Номер поставки,Предмет,Код номенклатуры,Бренд,Артикул поставщика,Название,Размер,Баркод,Тип документа,...,Тип коробов,Номер таможенной декларации,Код маркировки,ШК,Rid,Srid,Возмещение издержек по перевозке,Организатор перевозки,NEW COLUMN 111,report_number
0,17216947370,0,Юбки,119002337,Round&Round,YBSRtweedYBSRtweed,Юбка мини в клетку твидовая прямая трапеция,L,2036942380502,Продажа,...,Без коробов,NaN,NaN,8828752211,6.038226e+11,22028041580958001.2.0,NaN,NaN,test,111

In [19]:
def check_columns(df_1, df_2, report_name):
    # all columns for both dfs:
    main_columns = list(df_1.columns)
    new_columns = list(df_2.columns)
    # lists for absent columns:
    main_columns_absent = []
    new_columns_absent = []
    # filling list of missing columns:
    for main_column in main_columns:
        if main_column not in new_columns:
            main_columns_absent.append(main_column)
    for new_column in new_columns:
        if new_column not in main_columns:
            new_columns_absent.append(new_column)
    # print response:
    if len(main_columns_absent) == 0 and len(new_columns_absent) == 0:
        print('1')
        print('Все Ок набор колонок совпадает')
    else:
        if len(main_columns_absent) > 0 and len(new_columns_absent) > 0:
            print('2')
            print(f'В новом файле: {report_name} нет колонок: {main_columns_absent}')
            print(f'В новом файле: {report_name} появились новые колонки: {new_columns_absent}')
        elif len(main_columns_absent) > 0:
            print('3')
            print(f'В новом файле: {report_name} нет колонок: {main_columns_absent}')
            print('Удалить эти колонки из источника данных?')
        else:
            print('4')
            print(f'В новом файле: {report_name} появились новые колонки: {new_columns_absent}')
    return main_columns_absent, new_columns_absent

# use search function:
main_columns_absent, new_columns_absent = check_columns(df_result, df_111)
print(main_columns_absent, new_columns_absent)

4
В новом файле: 41866596 появились новые колонки: ['NEW COLUMN 111']
[] ['NEW COLUMN 111']

In [20]:
# try to concat:
pd.concat([df_result, df_111])

,№,Номер поставки,Предмет,Код номенклатуры,Бренд,Артикул поставщика,Название,Размер,Баркод,Тип документа,...,Тип коробов,Номер таможенной декларации,Код маркировки,ШК,Rid,Srid,Возмещение издержек по перевозке,Организатор перевозки,report_number,NEW COLUMN 111
0,17003963095,11082612,Юбки,44573138,Round&Round,YBBHblackleatherчернаякожаная,Юбка кожаная миди карандаш с разрезом длинная,L,2020837551009,Продажа,...,Микс,NaN,NaN,9317390808,6.037198e+11,56668891080620887.0.0,NaN,NaN,41866595,NaN
1,17003963096,10985000,Юбки,44573138,Round&Round,YBBHblackleatherчернаякожаная,Юбка кожаная миди карандаш с разрезом длинная,S,2011094378003,Продажа,...,Микс,NaN,NaN,9501601000,6.037792e+11,37629569080815299.0.0,NaN,NaN,41866595,NaN
2,17003963097,10985000,Юбки,44573138,Round&Round,YBBHblackleatherчернаякожаная,Юбка кожаная миди карандаш с разрезом длинная,S,2011094378003,Продажа,...,Микс,NaN,NaN,9501601000,6.037792e+11,37629569080815299.0.0,NaN,NaN,41866595,NaN
3,17003963098,10583426,Джинсы,136682537,Six Reasons,ДЖИНСЫmom,Укороченные джинсы мом с высокой посадкой,XL,2037193234224,Продажа,...,Микс,NaN,NaN,8791068856,0.000000e+00,52049433579842639.5.0,NaN,NaN,41866595,NaN
4,17003963099,10583426,Джинсы,136682537,Six Reasons,ДЖИНСЫmom,Укороченные джинсы мом с высокой посадкой,XL,2037193234224,Продажа,...,Микс,NaN,NaN,8791068856,0.000000e+00,52049433579842639.5.0,NaN,NaN,41866595,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25255,17216973926,14002091,Юбки,33915314,Round&Round,YBRR0507YBRRblack,Летняя юбка миди с разрезом трапеция,XS,2038376783638,Продажа,...,NaN,NaN,NaN,11771802943,NaN,NaN,3.121,Индивидуальный предприниматель Коробов Максим ...,111,NaN
25256,17216973927,14002091,Юбки,104401578,Round&Round,BLACKshelkRAZREZ,Юбка трапеция миди шелковая с разрезом атласная,M,2036869731951,Продажа,...,NaN,NaN,NaN,11771802551,NaN,NaN,4.065,ИП Шутраева Светлана Анатольевна(245200368144),111,NaN
25257,17216973928,14002091,Юбки,33915315,Round&Round,YBRR0507YBRRwhite,Летняя юбка миди с разрезом трапеция,XS,2038376807495,Продажа,...,NaN,NaN,NaN,11771802011,NaN,NaN,4.604,Апостолов Владимир Сергеевич(230408888242),111,NaN
25258,17216973932,14002091,Юбки,44573138,Round&Round,YBBHblackleatherчернаякожаная,Юбка кожаная миди карандаш с разрезом длинная,XS,2020837507006,Продажа,...,NaN,NaN,NaN,11771801911,NaN,NaN,2.927,Индивидуальный предприниматель Серков Леонид Ю...,111,NaN
25259,17216973934,14002091,Юбки,33915315,Round&Round,YBRR0507YBRRwhite,Летняя юбка миди с разрезом трапеция,XS,2038376807495,Продажа,...,NaN,NaN,NaN,11704374558,NaN,NaN,5.873,ИП Андрианова Дарья Викторовна(236504345401),111,test